
             [
               {
                 "id": "1",
                first name: "samuel",
                last name: "asres",
                citizen: "usa",
                date of birth: "02.25.1994",
              },
                 {
                   "id": "2",
                first name: "tigi",
                last name: "haile",
                citizen: "usa",
                date of birth: "02.25.1994",
              }
             ]