#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: this api seporrt mare
describedBy:
  headers:
    Autorization:
      description: mare users are happy
      type: string
  queryParameters:
    acess_token:
    description:
      type: string
  responses:
    400:
      body:
        application/json:
          example:
            {
              "massege": "sorry its not found"
            }
    401:
      body:
        application/json:
          example:
            {
              "massege": "unauterized"
            }



